---
  loss:
    - "squared_error"
    - "absolute_error"
    - "huber"
    - "quantile"
  learning_rate:
    - 0.1
    - 0.05
  max_iter:
    - 100
    - 50
  l2_regularization:
    - 0
    - 0.15
    - 0.3
  n_iter_no_change:
    - 5
    - 10
    - 15
  random_state:
    - 432
