---
  criterion:
    - "squared_error"
    - "absolute_error"
    - "poisson"
    - "friedman_mse"
  max_features:
    - "sqrt"
    - "log2"
    - None
  n_jobs:
    - -1
  ccp_alpha:
    - 0
    - .15
    - .3
  random_state:
    - 432
